core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('user.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index_view, name='index'),
    path('contacts', views.contacts_view, name='contacts'),

    path('game_product/<int:game_product_id>/', views.game_product_detail_view, name='game_product_detail'),
    path('game_product/create/', views.game_product_create_view, name='game_product_create'),
    path('game_product/update/<int:game_product_id>/', views.game_product_update_view, name='game_product_update'),
    path('game_product/<int:game_product_id>/delete/', views.game_product_delete_view, name='game_product_delete'),

    path('rating/create/<int:game_product_id>/', views.rating_create_view, name='rating_create'),
    path('rating-answer/create/<int:rating_id>/', views.rating_answer_create_view, name='rating_answer_create'),

    path('profile/', views.user_profile_view, name='user_profile'),
    
    path('payment_requests/', views.payment_request_list_view, name='payment_requests'),
    path('payment_request/<int:payment_request_id>/update/', views.payment_request_update_status,
         name='payment_request_update_status'),
    path('payments/', views.payment_list_view, name='payments'),

    path('game_product/<int:game_product_id>/payment/create/', views.game_product_payment_create_view,
         name='game_product_payment_create'),

    path('catalog/', views.game_product_list_view, name='catalog')
]

core/main/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from .choices import OrderStatusEnum

User = get_user_model()


class Category(models.Model):
    title = models.CharField(
        max_length=123,
        verbose_name='Название'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Image(models.Model):
    file = models.ImageField(
        upload_to='media/product_file',
        verbose_name='Файл'
    )

    def __str__(self):
        return str(self.file)

    class Meta:
        verbose_name = 'Изображение продукта'
        verbose_name_plural = 'Изображения продуктов'


#  TODO: Cделать связь на таблицу User
class Game_Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(
        max_length=123,
        verbose_name='Название'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        verbose_name='Категория'
    )
    main_image = models.ImageField(
        upload_to='media/main_covers',
        verbose_name='Главное фото',
        help_text='Фото которое будет отобрадажаться на обложке объявления'
    )
    images = models.ManyToManyField(
        Image,
        verbose_name='Изображения'
    )
    description = models.TextField(
        verbose_name='Описание'
    )
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='Цена'
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='Активен'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game_product = models.ForeignKey(
        Game_Product,
        on_delete=models.CASCADE,
        verbose_name='Игра'
    )
    count = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        verbose_name='Оценка'
    )
    comment = models.TextField(
        max_length=500,
        verbose_name='Комментарий'
    )
    created_date = models.DateTimeField(
        verbose_name='Дата создания',
        auto_now_add=True
    )

    def __str__(self):
        return f'{self.user} --> {self.game_product}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class RatingAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.ForeignKey(
        Rating,
        on_delete=models.CASCADE,
        verbose_name='Отзыв',
        related_name='rating_answers'
    )
    comment = models.TextField(
        max_length=500,
        verbose_name='Комментарий'
    )
    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )
    update_date = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата изменения'
    )
    time_limit = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name='Ограничение по вермени'
    )

    class Meta:
        verbose_name = 'Ответ на отзыв'
        verbose_name_plural = 'Ответы на отзывы'

    def __str__(self):
        return f'{self.user} --> {self.rating}'


class PaymentMethod(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='payment_methods',
        verbose_name='Пользователь'
    )
    title = models.CharField(
        max_length=123,
        verbose_name='Название'
    )
    qr_image = models.ImageField(
        upload_to='media/qr',
        verbose_name='QR'
    )
    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )

    class Meta:
        verbose_name = 'Способ оплаты'
        verbose_name_plural = 'Способы оплаты'

    def __str__(self):
        return f"{self.user} --> {self.title}"


class PaymentRequest(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='orders',
        verbose_name='Пользователь'
    )
    game_product = models.ForeignKey(
        Game_Product,
        on_delete=models.CASCADE,
        verbose_name='Игра',
        related_name='orders'
    )
    is_paid = models.BooleanField(
        verbose_name='Приянто',
        default=False
    )
    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )
    update_date = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата изменения'
    )
    quantity = models.PositiveSmallIntegerField(
        verbose_name='Количество',
        default=1
    )
    check_image = models.ImageField(
        verbose_name='Чек',
        upload_to='media/check'
    )
    total_price = models.PositiveIntegerField(
        verbose_name='Сумма'
    )

    status = models.CharField(
        choices=OrderStatusEnum.choices,
        default=OrderStatusEnum.IN_PROCESSING,
        verbose_name='Статус оплаты',
        max_length=15
    )

    class Meta:
        verbose_name = 'Заявка на оплату'
        verbose_name_plural = 'Заявки на оплату'

    def __str__(self):
        return f"{self.user} --> {self.game_product}"


class Payment(models.Model):
    seller = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    user = models.CharField(
        max_length=225,
        verbose_name='Покупатель'
    )
    game_product = models.CharField(
        max_length=225,
        verbose_name='Продукт'
    )
    quantity = models.PositiveSmallIntegerField(
        verbose_name='Количество'
    )
    check_image = models.ImageField(
        verbose_name='Чек',
        upload_to='media/check'
    )
    total_price = models.PositiveIntegerField(
        verbose_name='Сумма'
    ) 
    created_date = models.DateTimeField(
        auto_now_add=True,
    )
    

    class Meta:
        verbose_name = 'Оплата'
        verbose_name_plural = 'Оплаты'

core/main/forms.py
from django import forms
from .models import Game_Product

class GameProductCreateForm(forms.ModelForm):
    class Meta:
        model = Game_Product
        fields = (
            'title',
            'category',
            'main_image',
            'images',
            'description',
            'price',
        )

class GameProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Game_Product
        fields = (
            'title',
            'category',
            'main_image',
            'images',
            'description',
            'price',
        )

core/main/views.py
from decimal import Decimal

from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.contrib import messages
from django.db.models import Avg, Sum
from django.core.paginator import Paginator

from .forms import GameProductCreateForm, GameProductUpdateForm
from .filters import GameProductListFilter
from .models import Game_Product, Rating, RatingAnswer, PaymentMethod, PaymentRequest, Category, Payment


def index_view(request):
    game_products = Game_Product.objects.filter(is_active=True)

    return render(request, 'main/index.html', {"game_products": game_products})

def contacts_view(request):
    return render(request, 'main/contact.html')

def game_product_detail_view(request, game_product_id):
    game_product = get_object_or_404(Game_Product, id=game_product_id)
    game_product_update_form = GameProductUpdateForm(instance=game_product)
    game_product_comments = Rating.objects.filter(game_product=game_product)

    game_products_with_ratings = []

    rating_avg = game_product_comments.aggregate(Avg('count'))['count__avg']
    similar_game_products = Game_Product.objects.filter(category=game_product.category).exclude(id=game_product.id)

    game_products_with_ratings.append({
        'product': game_product,
        'rating_avg': rating_avg
    })

    return render(
        request=request,
        template_name='main/game_product_detail.html',
        context={
            "game_product": game_product,
            "similar_game_products": similar_game_products,
            "game_product_update_form": game_product_update_form,
            "game_product_comments": game_product_comments,
            "rating_avg": rating_avg
        })


def game_product_create_view(request):
    if not request.user.is_authenticated:
        raise Http404()

    if request.method == 'POST':
        form = GameProductCreateForm(request.POST, request.FILES)
        if form.is_valid():
            game_product_object = form.save(commit=False)
            game_product_object.user = request.user
            game_product_object.save()

            messages.success(request, 'Успешно создано!')
            return redirect('index')

    form = GameProductCreateForm()
    return render(request, 'main/game_product_create.html', {"form": form})


def game_product_update_view(request, game_product_id):
    game_product = get_object_or_404(Game_Product, id=game_product_id)

    if request.method == 'POST':
        form = GameProductUpdateForm(request.POST, request.FILES, instance=game_product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Успешно изменено!')
            return redirect('game_product_detail', game_product_id)

def game_product_delete_view(request, game_product_id):
    game_product = get_object_or_404(Game_Product, id=game_product_id)

    if request.method == "POST":
        game_product.delete()
        messages.success(request, "Товар успешно удален!")
        return redirect("index") 

    return redirect("game_product_detail", game_product_id)


def rating_create_view(request, game_product_id):
    game_product = get_object_or_404(Game_Product, id=game_product_id)

    if not request.user.is_authenticated:
        messages.error(request, 'Только авторизованные!')
        return redirect('game_product_detail', game_product_id)

    if request.method == 'POST':
        comment = request.POST.get('comment', '')
        count = int(request.POST.get('count', ''))

        rating = Rating(
            user=request.user,
            game_product=game_product,
            count=count,
            comment=comment
        )
        rating.save()
        messages.success(request, 'Спасибо за отзыв!')
        return redirect('game_product_detail', game_product_id)


def rating_answer_create_view(request, rating_id):
    rating = get_object_or_404(Rating, id=rating_id)

    if rating.game_product.user != request.user:
        messages.error(request, 'Нету доступа')
        return redirect('game_product_detail', rating.game_product.id)

    if request.method == 'POST':
        comment = request.POST.get('comment', '')

        rating_answer = RatingAnswer(
            user=request.user,
            rating=rating,
            comment=comment
        )

        rating_answer.save()

        messages.success(request, 'Успешно отправлено')
        return redirect('game_product_detail', rating.game_product.id)


def user_profile_view(request):
    if not request.user.is_authenticated:
        messages.error(request, 'Только авторизованные!')
        return redirect('index' )
    
    payment_requests = PaymentRequest.objects.filter(game_product__user=request.user, status='in_processing').order_by('-id')[:3]
  
    return render(
        request=request,
        template_name='main/user_profile.html',
        context={
            'payment_requests': payment_requests
        }
    )


def game_product_payment_create_view(request, game_product_id):
    game_product = get_object_or_404(Game_Product, id=game_product_id)
    seller_payment_methods = PaymentMethod.objects.filter(user=game_product.user)

    if request.method == 'POST':
        check = request.FILES.get('check', '')
        quantity = request.POST.get('quantity')

        total_price = Decimal(quantity) * game_product.price

        order = PaymentRequest(
            user=request.user,
            game_product=game_product,
            quantity=quantity,
            check_image=check,
            total_price=total_price
        )
        order.save()
        messages.success(request, 'Заявку на оплату отправлена продавцу')
        return redirect('index')

    return render(
        request=request,
        template_name='main/game_product_payment.html',
        context={
            "seller_payment_methods": seller_payment_methods
        }
    )
def game_product_list_view(request):
    queryset = Game_Product.objects.filter(is_active=True)
    queryset = queryset.annotate(avg_rating=Avg('rating__count'))

    if 'game_product_search' in request.GET:
        game_product_name = request.GET.get("game_product_search")
        queryset = queryset.filter(title__icontains=game_product_name)

    game_products = GameProductListFilter(request.GET, queryset=queryset)

    # Paginator
    paginator = Paginator(game_products.qs, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request, 
        'main/game_product_list.html', 
        {'page_obj': page_obj, 
         'game_products': game_products,
         'avg_ratings': {product.id: product.avg_rating for product in queryset}
         })


def payment_request_list_view(request):
    payment_requests = PaymentRequest.objects.filter(game_product__user=request.user).order_by('-id')

    return render(
        request=request,
        template_name='main/payment_request.html',
        context={
            'payment_requests': payment_requests
        }
    )


def payment_request_update_status(request, payment_request_id):
    payment_request = get_object_or_404(PaymentRequest, id=payment_request_id)

    if request.method == 'POST':
        status = request.POST.get('status')
        payment_request.status = status
        payment_request.save()

        if payment_request.status == 'accepted':

            payment = Payment(
                seller=payment_request.game_product.user,
                user=payment_request.user.first_name,
                game_product=payment_request.game_product.title,
                quantity=payment_request.quantity,
                check_image=payment_request.check_image,
                total_price=payment_request.total_price
            )
            payment.save()

        messages.success(request, 'Успешно изменено')

    return redirect('payment_requests')


def payment_list_view(request):
    payments = Payment.objects.filter(seller=request.user)

    total_payments = payments.aggregate(Sum('total_price'))['total_price__sum']

    return render(
        request=request,
        template_name='main/payments.html',
        context={
            "payments": payments,
            "total_payments": total_payments
        }
    )

core/main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>


</style>

  <div class="page-heading header-text">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h3>Contact Us</h3>
          <span class="breadcrumb"><a href="#">Home</a>  >  Contact Us</span>
        </div>
      </div>
    </div>
  </div>

  <div class="contact-page section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="left-text">
            <div class="section-heading">
              <h6>Contact Us</h6>
              <h2>Say Hello!</h2>
            </div>
            <p>LUGX Gaming Template is based on the latest Bootstrap 5 CSS framework. This template is provided by TemplateMo and it is suitable for your gaming shop ecommerce websites. Feel free to use this for any purpose. Thank you.</p>
            <ul class="contact-info">
              <li><span>Address: Sunny Isles Beach, FL 33160, United States</span> </li>
              <li><span>Phone: +123 456 7890</span> </li>
              <li><span>Email: lugx@contact.com </span> </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="right-content">
            <div class="row">
              <div class="col-lg-12">
                <div id="map">
                  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12469.776493332698!2d-80.14036379941481!3d25.907788681148624!2m3!1f357.26927939317244!2f20.870722720054623!3f0!3m2!1i1024!2i768!4f35!3m3!1m2!1s0x88d9add4b4ac788f%3A0xe77469d09480fcdb!2sSunny%20Isles%20Beach!5e1!3m2!1sen!2sth!4v1642869952544!5m2!1sen!2sth" width="100%" height="325px" frameborder="0" style="border:0; border-radius: 23px;" allowfullscreen=""></iframe>
                </div>
              </div>
              <div class="col-lg-12">
                <form id="contact-form" action="" method="post">
                  <div class="row">
                    <div class="col-lg-6">
                      <fieldset>
                        <input type="name" name="name" id="name" placeholder="Your Name..." autocomplete="on" required>
                      </fieldset>
                    </div>
                    <div class="col-lg-6">
                      <fieldset>
                        <input type="surname" name="surname" id="surname" placeholder="Your Surname..." autocomplete="on" required>
                      </fieldset>
                    </div>
                    <div class="col-lg-6">
                      <fieldset>
                        <input type="text" name="email" id="email" pattern="[^ @]*@[^ @]*" placeholder="Your E-mail..." required=""/>
                      </fieldset>
                    </div>
                    <div class="col-lg-6">
                      <fieldset>
                        <input type="subject" name="subject" id="subject" placeholder="Subject..." autocomplete="on" />
                      </fieldset>
                    </div>
                    <div class="col-lg-12">
                      <fieldset>
                        <textarea name="message" id="message" placeholder="Your Message"></textarea>
                      </fieldset>
                    </div>
                    <div class="col-lg-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="orange-button">Send Message Now</button>
                      </fieldset>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>  

{% endblock %}

core/main/templates/main/game_product_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    /* Стили для формы создания продукта */
    .create-product-container {
        background-color: #1f1f1f;
        border-radius: 10px;
        padding: 30px;
        margin-top: 50px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
    }
    
    .create-product-title {
        color: #311791;
        font-size: 28px;
        margin-bottom: 30px;
        text-align: center;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
    
    .login-form {
        background-color: #2a2a2a;
        border-radius: 8px;
        padding: 30px;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    }
    
    .form-group {
        margin-bottom: 25px;
    }
    
    .form-group label {
        color: #fff;
        display: block;
        margin-bottom: 8px;
        font-weight: 500;
    }
    
    .form-control {
        width: 100%;
        padding: 12px 15px;
        background-color: #333;
        border: 1px solid #444;
        border-radius: 6px;
        color: #fff;
        font-size: 16px;
    }
    
    .form-control:focus {
        border-color: #0b088f;
        box-shadow: 0 0 0 3px rgba(236, 96, 144, 0.2);
        outline: none;
    }
    
    .main-border-button {
        background: linear-gradient(135deg, #ec6090 0%, #4a2fbd 100%);
        color: white;
        border: none;
        padding: 12px 30px;
        border-radius: 25px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 1px;
        cursor: pointer;
        transition: all 0.3s ease;
        margin-top: 20px;
    }
    
    .main-border-button:hover {
        transform: translateY(-3px);
        box-shadow: 0 10px 20px rgba(236, 96, 144, 0.3);
    }
    
    .register-link {
        color: #0c0b6e;
        text-decoration: none;
        transition: all 0.3s ease;
    }
    
    .register-link:hover {
        color: #fff;
        text-decoration: underline;
    }
    
    /* Стили для файловых полей */
    .file-upload {
        position: relative;
        margin-bottom: 20px;
    }
    
    .file-upload-label {
        display: block;
        padding: 15px;
        background: #333;
        border: 2px dashed #444;
        border-radius: 8px;
        text-align: center;
        color: #aaa;
        cursor: pointer;
        transition: all 0.3s ease;
    }
    
    .file-upload-label:hover {
        border-color: #0f1894;
        color: #fff;
    }
</style>

<!-- ***** Main Content Start ***** -->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="create-product-container">
                <h2 class="create-product-title">Создание продукта</h2>
                
                {% if messages %}
                <div class="mb-4">
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                
                <div class="login-form">
                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label for="id_title">Название</label>
                            {{ form.title }}
                        </div>
                        
                        <div class="form-group">
                            <label for="id_category">Категория</label>
                            {{ form.category }}
                        </div>
                        
                        <div class="form-group">
                            <label>Главное изображение</label>
                            <div class="file-upload">
                                <label class="file-upload-label" for="id_main_image">
                                    <i class="fas fa-cloud-upload-alt me-2"></i>Выберите файл
                                    <span class="d-block small mt-2">Перетащите или кликните для загрузки</span>
                                </label>
                                {{ form.main_image }}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label>Дополнительные изображения</label>
                            <div class="file-upload">
                                <label class="file-upload-label" for="id_images">
                                    <i class="fas fa-images me-2"></i>Выберите файлы
                                    <span class="d-block small mt-2">Можно выбрать несколько изображений</span>
                                </label>
                                {{ form.images }}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="id_description">Описание</label>
                            {{ form.description }}
                        </div>
                        
                        <div class="form-group">
                            <label for="id_price">Цена ($)</label>
                            {{ form.price }}
                        </div>
                        
                        <div class="text-center">
                            <button type="submit" class="main-border-button">Создать продукт</button>
                        </div>
                    </form>
                    
                    <div class="text-center mt-4">
                        <span style="color: #aaa;">Ещё нет аккаунта?</span>
                        <a href="{% url 'register' %}" class="register-link">Зарегистрироваться</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Main Content End ***** -->

<script>
// Скрипт для отображения имени выбранного файла
document.addEventListener('DOMContentLoaded', function() {
    const fileInputs = document.querySelectorAll('input[type="file"]');
    
    fileInputs.forEach(input => {
        const label = input.previousElementSibling;
        const span = label.querySelector('span');
        
        input.addEventListener('change', function() {
            if (this.files && this.files.length > 0) {
                if (this.files.length > 1) {
                    span.textContent = `Выбрано файлов: ${this.files.length}`;
                } else {
                    span.textContent = this.files[0].name;
                }
            } else {
                span.textContent = this.multiple ? 
                    'Можно выбрать несколько изображений' : 
                    'Перетащите или кликните для загрузки';
            }
        });
    });
});
</script>

{% endblock %}

core/main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <!-- Main Banner Section -->
  <div class="main-banner">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          {% if messages %}
            <div class="messages-container">
              <!-- Loop through messages and display them -->
              {% for message in messages %}
                <div class="alert
                  {% if message.tags == 'error' %} alert-danger
                  {% elif message.tags == 'success' %} alert-success
                  {% elif message.tags == 'warning' %} alert-warning
                  {% else %} alert-info {% endif %} 
                  alert-dismissible fade show" role="alert">
                  
                  <!-- Display message -->
                  <strong>{% if message.tags == 'success' %}Success!{% elif message.tags == 'error' %}Error!{% elif message.tags == 'warning' %}Warning!{% else %}Note{% endif %}:</strong>
                  {{ message }}
                  
                  <!-- Button to close the alert -->
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              {% endfor %}
            </div>
          {% endif %}

          <!-- Banner Content -->
          <div class="caption header-text">
            <h6>Welcome to lugx</h6>
            <h2>BEST GAMING SITE EVER!</h2>
            <p>LUGX Gaming is free Bootstrap 5 HTML CSS website template for your gaming websites. You can download and use this layout for commercial purposes. Please tell your friends about TemplateMo.</p>

      <!-- Search Form in the Banner -->
            <div class="search-input">
              <form id="search" action="{% url 'catalog' %}" method="get">
                <input type="text" placeholder="Type Something" id='searchText' name="game_product_search" onkeypress="handle" />
                <button type="submit"><i class="fa fa-search"></i></button>
              </form>
            </div> 
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Trending Games Section -->
  <div class="section trending">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="section-heading">
            <h6>Trending</h6>
            <h2>Trending Games</h2>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="main-button">
            <a href="shop.html">View All</a>
          </div>
        </div>
        {% for game_product in game_products %}
          <div class="col-lg-3 col-md-6">
            <div class="item">
              <div class="thumb">
                <a href="{% url 'game_product_detail' game_product.id %}"><img src="{{ game_product.main_image.url }}" alt=""></a>
                <span class="price">{{ game_product.price }}$</span>
              </div>
              <div class="down-content">
                <span class="category">Action</span>
                <h4>{{ game_product.title }}</h4>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}